### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by kamikatze2008** [lovejjfg/PowerText#2]
I have a problem - when I invoke
` setOriginalText(Spannable spannable) `
I can see my formatted text only when text is expanded, but when it is folded - all Spans are gone.
Could you fix that, please?

**Comment by lovejjfg** [comment]
ok , I'll  try to support it soon.

**Comment by lovejjfg** [comment]
https://github.com/lovejjfg/PowerText/releases/tag/0.0.5

**Comment by kamikatze2008** [comment]
I've updated library version and nothing has changed - I've recorded you a video regarding that functionality - mention that first two words are not bold in folded state, and bold, when they are expanded.
Also I've found a second bug regarding view redrawing.
https://drive.google.com/open?id=1CeqTYWSOQa_rV5otxOl-1BYd-YBzXHNz

**Comment by lovejjfg** [comment]
oh , I'm so sorry to apply so late. In version 0.0.5, i supported `SpannableString `. so what about you The data source？It's html ？
